osx_image: xcode9.1
language: objective-c
script:
    - xcodebuild clean build -sdk iphonesimulator -project gasonframework.xcodeproj -scheme gasonframewoekTestsScheme build test CODE_SIGNING_REQUIRED=NO
